// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypybkscaaoicaaapszbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweWJrc2NhYW9pY2FhYXBzemJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMDc4NTUsImV4cCI6MjA4Nzg4Mzg1NX0.t-hQwvdbB3EPxLUKpQncZJXiKyuiUfC-i8MuwX5G32Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});